import assert from 'node:assert/strict';
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { NOTE_PHRASES } from '../src/notePhrases.js';
import { validateDialogueRecords } from '../src/dialogue/index.js';

const rulesPath = new URL('../firestore.rules', import.meta.url);
const world = JSON.parse(await readFile(new URL('../src/world.json', import.meta.url), 'utf8'));
const mimarRecords = JSON.parse(await readFile(new URL('../src/dialogue/mimar.json', import.meta.url), 'utf8'));
const dialogueValidation = validateDialogueRecords(mimarRecords, world);
validateInputs(world, NOTE_PHRASES, dialogueValidation.knownFlags);

const rules = generateRules(world, NOTE_PHRASES, dialogueValidation.knownFlags);
const estimate = estimateWorstCaseExpressions(world, NOTE_PHRASES, dialogueValidation.knownFlags);
reportEstimate(estimate);

if (process.argv.includes('--check')) {
  const committedRules = await readFile(rulesPath, 'utf8');
  assert.equal(committedRules, rules, 'firestore.rules güncel değil; npm run gen:rules çalıştırın');
  console.log('firestore.rules world.json ve notePhrases.js ile birebir güncel');
} else {
  await writeFile(rulesPath, rules, 'utf8');
  console.log(`firestore.rules üretildi: ${fileURLToPath(rulesPath)}`);
}

function generateRules(data, phrases, mimarFlags) {
  const regionIds = data.regions.map(({ id }) => id);
  const islandIds = data.islands.map(({ id }) => id);
  const bridgeIds = data.bridges.map(({ id }) => id);
  const regionBridgeIds = data.regionBridges.map(({ id }) => id);
  const phraseIds = phrases.map(({ id }) => id);
  const mimarFlagIds = [...mimarFlags];
  const islandPattern = exactPattern(islandIds);
  const regionPattern = exactPattern(regionIds);
  const phrasePattern = exactPattern(phraseIds);
  const playerFields = [
    'nickname', 'createdAt', 'lastSeenAt', 'activeRegionId', 'currentIslandId',
    'solvedCount', 'solved', 'openBridges', 'openRegionBridges', 'mimarFlags', 'schemaVersion',
  ];
  const regionIslandChecks = data.regions.map((region, index) => {
    const prefix = index === 0 ? '        (' : '        || (';
    return `${prefix}data.activeRegionId == '${region.id}' && data.currentIslandId.matches('${exactPattern(region.islands)}'))`;
  }).join('\n');

  return `// Generated by scripts/gen-rules.mjs from src/world.json and src/notePhrases.js. Do not edit.
rules_version = '2';

service cloud.firestore {
  match /databases/{database}/documents {
    function signedIn() {
      return request.auth != null;
    }

    function owns(uid) {
      return signedIn() && request.auth.uid == uid;
    }

    function validIslandId(value) {
      return value is string && value.matches('${islandPattern}');
    }

    function validRegionId(value) {
      return value is string && value.matches('${regionPattern}');
    }

    function validPhraseId(value) {
      return value is string && value.matches('${phrasePattern}');
    }

    function shardMatches(pathId, numericId) {
      return ${Array.from({ length: 10 }, (_, index) => `${index ? '|| ' : ''}(pathId == '${index}' && numericId == ${index})`).join('\n        ')};
    }

    function playerAfter(uid) {
      return getAfter(/databases/$(database)/documents/players/$(uid)).data;
    }

    function contributionBefore(uid) {
      return get(/databases/$(database)/documents/aggregateContributions/$(uid)).data;
    }

    function contributionAfter(uid) {
      return getAfter(/databases/$(database)/documents/aggregateContributions/$(uid)).data;
    }

    function validNickname(nickname) {
      return nickname is string && nickname.size() >= 3 && nickname.size() <= 40;
    }

    function validRegionAndIsland(data) {
      return validRegionId(data.activeRegionId)
        && (
${regionIslandChecks}
        );
    }

    function validSolvedRecord(record) {
      return record is map
        && record.keys().hasAll(['solvedAt', 'durationMs', 'attempts'])
        && record.keys().hasOnly(['solvedAt', 'durationMs', 'attempts'])
        && (record.solvedAt == null || record.solvedAt is timestamp)
        && record.durationMs is int
        && record.durationMs >= 0
        && record.durationMs < 3600000
        && record.attempts is int
        && record.attempts > 0;
    }

    function validSolvedShape(solved) {
      return solved is map
        && solved.size() <= ${islandIds.length};
    }

    function validSolvedUpdate(after, before, currentIslandId) {
      let changedKeys = after.diff(before).affectedKeys();
      return changedKeys.size() == 0
        || after.size() == 0
        || (
          changedKeys.hasOnly([currentIslandId])
          && after.keys().hasAny([currentIslandId])
          && validSolvedRecord(after[currentIslandId])
        );
    }

    function validOpenBridges(value) {
      return value is list
        && value.size() <= ${bridgeIds.length}
        && value.size() == value.toSet().size()
        && value.hasOnly([
${formatList(bridgeIds, 10)}
        ]);
    }

    function validOpenRegionBridges(value) {
      return value is list
        && value.size() <= ${regionBridgeIds.length}
        && value.size() == value.toSet().size()
        && value.hasOnly([
${formatList(regionBridgeIds, 10)}
        ]);
    }

    function validMimarFlags(value) {
      return value is list
        && value.size() <= 64
        && value.size() == value.toSet().size()
        && value.hasOnly([
${formatList(mimarFlagIds, 10)}
        ]);
    }

    function validPlayer(data) {
      return data.keys().hasAll([
${formatList(playerFields, 10)}
        ]) && data.keys().hasOnly([
${formatList(playerFields, 10)}
        ])
        && data.schemaVersion == 1
        && validNickname(data.nickname)
        && data.createdAt is timestamp
        && data.lastSeenAt is timestamp
        && data.solvedCount is int
        && data.solvedCount >= 0
        && data.solvedCount <= ${islandIds.length}
        && validRegionAndIsland(data)
        && validSolvedShape(data.solved)
        && validOpenBridges(data.openBridges)
        && validOpenRegionBridges(data.openRegionBridges)
        && validMimarFlags(data.mimarFlags);
    }

    function validPlayerSolvedCountUpdate(after, before) {
      return !before.keys().hasAny(['solvedCount'])
        || after.solvedCount == before.solvedCount
        || after.solvedCount == before.solvedCount + 1
        || (after.solvedCount == 0 && after.solved.size() == 0);
    }

    function validLeaderboard(data, uid) {
      return data.keys().hasAll(['nickname', 'solvedCount', 'currentIslandId', 'activeRegionId', 'updatedAt'])
        && data.keys().hasOnly(['nickname', 'solvedCount', 'currentIslandId', 'activeRegionId', 'updatedAt'])
        && validNickname(data.nickname)
        && data.solvedCount is int
        && data.solvedCount >= 0
        && data.solvedCount <= ${islandIds.length}
        && validIslandId(data.currentIslandId)
        && validRegionId(data.activeRegionId)
        && data.updatedAt == request.time
        && data.nickname == playerAfter(uid).nickname
        && data.solvedCount == playerAfter(uid).solvedCount
        && data.currentIslandId == playerAfter(uid).currentIslandId
        && data.activeRegionId == playerAfter(uid).activeRegionId;
    }

    function validContribution(data) {
      return data.keys().hasAll([
          'registered', 'playerShard', 'solvedCount', 'lastSolvedShard',
          'lastSolvedIslandId', 'lastDurationMs', 'updatedAt'
        ])
        && data.keys().hasOnly([
          'registered', 'playerShard', 'solvedCount', 'lastSolvedShard',
          'lastSolvedIslandId', 'lastDurationMs', 'updatedAt'
        ])
        && data.registered == true
        && data.playerShard is int
        && data.playerShard >= 0 && data.playerShard < 10
        && data.solvedCount is int
        && data.solvedCount >= 0 && data.solvedCount <= ${islandIds.length}
        && (data.lastSolvedShard == null
          || (data.lastSolvedShard is int && data.lastSolvedShard >= 0 && data.lastSolvedShard < 10))
        && (data.lastSolvedIslandId == null || validIslandId(data.lastSolvedIslandId))
        && data.lastDurationMs is int
        && data.lastDurationMs >= 0 && data.lastDurationMs < 3600000
        && data.updatedAt == request.time;
    }

    function validSolveReceipt(data, uid, islandId) {
      return data.keys().hasAll(['shardId', 'durationMs', 'createdAt'])
        && data.keys().hasOnly(['shardId', 'durationMs', 'createdAt'])
        && data.shardId is int && data.shardId >= 0 && data.shardId < 10
        && data.durationMs is int && data.durationMs > 0 && data.durationMs < 3600000
        && data.createdAt == request.time
        && contributionAfter(uid).solvedCount == contributionBefore(uid).solvedCount + 1
        && contributionAfter(uid).lastSolvedShard == data.shardId
        && contributionAfter(uid).lastSolvedIslandId == islandId
        && contributionAfter(uid).lastDurationMs == data.durationMs
        && playerAfter(uid).solved.keys().hasAny([islandId])
        && playerAfter(uid).solved[islandId].solvedAt is timestamp;
    }

    function validCounter(data) {
      return data.keys().hasAll(['solved', 'players'])
        && data.keys().hasOnly(['solved', 'players'])
        && data.solved is int && data.solved >= 0
        && data.players is int && data.players >= 0;
    }

    match /players/{uid} {
      allow read: if owns(uid);
      allow create: if owns(uid)
        && validPlayer(request.resource.data)
        && request.resource.data.solvedCount == 0
        && request.resource.data.solved.size() == 0
        && request.resource.data.createdAt == request.time
        && request.resource.data.lastSeenAt == request.time
        && existsAfter(/databases/$(database)/documents/aggregateContributions/$(uid))
        && existsAfter(/databases/$(database)/documents/leaderboard/$(uid));
      allow update: if owns(uid)
        && validPlayer(request.resource.data)
        && validSolvedUpdate(request.resource.data.solved, resource.data.solved, request.resource.data.currentIslandId)
        && validPlayerSolvedCountUpdate(request.resource.data, resource.data)
        && request.resource.data.createdAt == resource.data.createdAt;
      allow delete: if false;
    }

    match /aggregateContributions/{uid} {
      allow read: if owns(uid);
      allow create: if owns(uid)
        && validContribution(request.resource.data)
        && request.resource.data.solvedCount == playerAfter(uid).solvedCount
        && request.resource.data.lastSolvedShard == null
        && request.resource.data.lastSolvedIslandId == null
        && request.resource.data.lastDurationMs == 0
        && existsAfter(/databases/$(database)/documents/leaderboard/$(uid));
      allow update: if owns(uid)
        && validContribution(request.resource.data)
        && request.resource.data.playerShard == resource.data.playerShard
        && request.resource.data.solvedCount == resource.data.solvedCount + 1
        && request.resource.data.lastSolvedIslandId != null
        && request.resource.data.lastSolvedShard != null
        && request.resource.data.lastDurationMs > 0
        && existsAfter(/databases/$(database)/documents/aggregateContributions/$(uid)/solves/$(request.resource.data.lastSolvedIslandId))
        && !exists(/databases/$(database)/documents/aggregateContributions/$(uid)/solves/$(request.resource.data.lastSolvedIslandId));
      allow delete: if false;
    }

    match /aggregateContributions/{uid}/solves/{islandId} {
      allow read: if owns(uid);
      allow create: if owns(uid)
        && validIslandId(islandId)
        && validSolveReceipt(request.resource.data, uid, islandId);
      allow update, delete: if false;
    }

    match /counters/global/shards/{shardId} {
      allow read: if true;
      allow create: if signedIn()
        && validCounter(request.resource.data)
        && (
          (request.resource.data.players == 1 && request.resource.data.solved == 0
            && shardMatches(shardId, contributionAfter(request.auth.uid).playerShard)
            && !exists(/databases/$(database)/documents/aggregateContributions/$(request.auth.uid)))
          || (request.resource.data.solved == 1 && request.resource.data.players == 0
            && shardMatches(shardId, contributionAfter(request.auth.uid).lastSolvedShard)
            && contributionAfter(request.auth.uid).solvedCount == contributionBefore(request.auth.uid).solvedCount + 1)
        );
      allow update: if signedIn()
        && validCounter(request.resource.data)
        && (
          (request.resource.data.players == resource.data.players + 1
            && request.resource.data.solved == resource.data.solved
            && shardMatches(shardId, contributionAfter(request.auth.uid).playerShard)
            && !exists(/databases/$(database)/documents/aggregateContributions/$(request.auth.uid)))
          || (request.resource.data.solved == resource.data.solved + 1
            && request.resource.data.players == resource.data.players
            && shardMatches(shardId, contributionAfter(request.auth.uid).lastSolvedShard)
            && contributionAfter(request.auth.uid).solvedCount == contributionBefore(request.auth.uid).solvedCount + 1)
        );
      allow delete: if false;
    }

    match /islandStats/{islandId} {
      allow read: if true;
      allow create: if signedIn()
        && validIslandId(islandId)
        && request.resource.data.keys().hasAll(['solvedCount', 'sumDurationMs'])
        && request.resource.data.keys().hasOnly(['solvedCount', 'sumDurationMs'])
        && request.resource.data.solvedCount == 1
        && request.resource.data.sumDurationMs == contributionAfter(request.auth.uid).lastDurationMs
        && contributionAfter(request.auth.uid).lastSolvedIslandId == islandId
        && contributionAfter(request.auth.uid).solvedCount == contributionBefore(request.auth.uid).solvedCount + 1;
      allow update: if signedIn()
        && validIslandId(islandId)
        && request.resource.data.keys().hasAll(['solvedCount', 'sumDurationMs'])
        && request.resource.data.keys().hasOnly(['solvedCount', 'sumDurationMs'])
        && request.resource.data.solvedCount == resource.data.solvedCount + 1
        && request.resource.data.sumDurationMs == resource.data.sumDurationMs + contributionAfter(request.auth.uid).lastDurationMs
        && contributionAfter(request.auth.uid).lastSolvedIslandId == islandId
        && contributionAfter(request.auth.uid).solvedCount == contributionBefore(request.auth.uid).solvedCount + 1;
      allow delete: if false;
    }

    match /leaderboard/{uid} {
      allow read: if true;
      allow create: if owns(uid) && validLeaderboard(request.resource.data, uid);
      allow update: if owns(uid)
        && validLeaderboard(request.resource.data, uid)
        && (
          request.resource.data.solvedCount == resource.data.solvedCount
          || request.resource.data.solvedCount == resource.data.solvedCount + 1
          || request.resource.data.solvedCount == 0
        );
      allow delete: if false;
    }

    match /noteChoices/{uid}/islands/{islandId} {
      allow read: if owns(uid);
      allow create: if owns(uid)
        && validIslandId(islandId)
        && request.resource.data.keys().hasAll(['phraseId', 'createdAt'])
        && request.resource.data.keys().hasOnly(['phraseId', 'createdAt'])
        && validPhraseId(request.resource.data.phraseId)
        && request.resource.data.createdAt == request.time
        && playerAfter(uid).solved.keys().hasAny([islandId])
        && playerAfter(uid).solved[islandId].solvedAt is timestamp
        && (
          (!exists(/databases/$(database)/documents/notes/$(islandId)/entries/$(request.resource.data.phraseId))
            && getAfter(/databases/$(database)/documents/notes/$(islandId)/entries/$(request.resource.data.phraseId)).data.count == 1)
          || (exists(/databases/$(database)/documents/notes/$(islandId)/entries/$(request.resource.data.phraseId))
            && getAfter(/databases/$(database)/documents/notes/$(islandId)/entries/$(request.resource.data.phraseId)).data.count
              == get(/databases/$(database)/documents/notes/$(islandId)/entries/$(request.resource.data.phraseId)).data.count + 1)
        );
      allow update, delete: if false;
    }

    match /notes/{islandId}/entries/{phraseId} {
      allow read: if true;
      allow create: if signedIn()
        && validIslandId(islandId)
        && request.resource.data.keys().hasOnly(['count'])
        && request.resource.data.count == 1
        && !exists(/databases/$(database)/documents/noteChoices/$(request.auth.uid)/islands/$(islandId))
        && getAfter(/databases/$(database)/documents/noteChoices/$(request.auth.uid)/islands/$(islandId)).data.phraseId == phraseId;
      allow update: if signedIn()
        && validIslandId(islandId)
        && request.resource.data.keys().hasOnly(['count'])
        && request.resource.data.count == resource.data.count + 1
        && !exists(/databases/$(database)/documents/noteChoices/$(request.auth.uid)/islands/$(islandId))
        && getAfter(/databases/$(database)/documents/noteChoices/$(request.auth.uid)/islands/$(islandId)).data.phraseId == phraseId;
      allow delete: if false;
    }

    match /{document=**} {
      allow read, write: if false;
    }
  }
}
`;
}

function estimateWorstCaseExpressions(data, phrases, mimarFlags) {
  const generatedLiterals = data.bridges.length + data.regionBridges.length
    + data.regions.length + phrases.length + mimarFlags.size + 20;
  return { estimated: 250 + generatedLiterals, warningAt: 750, limit: 1000 };
}

function reportEstimate({ estimated, warningAt, limit }) {
  console.log(`Rules ifade tahmini: ${estimated}/${limit} (%${Math.round(estimated / limit * 100)})`);
  if (estimated >= limit) throw new Error(`Tahmini rules ifade maliyeti ${limit} sınırını aşıyor`);
  if (estimated >= warningAt) console.warn(`UYARI: Tahmini rules maliyeti ${warningAt} uyarı eşiğine ulaştı`);
}

function validateInputs(data, phrases, mimarFlags) {
  for (const key of ['regions', 'islands', 'bridges', 'regionBridges']) {
    assert.ok(Array.isArray(data[key]), `world.json ${key} listesi içermeli`);
  }
  assert.ok(phrases.length >= 24, 'En az 24 not cümlesi olmalı');
  assert.ok(mimarFlags.size > 0 && mimarFlags.size <= 64, 'Mimar flag sayısı 1–64 olmalı');
  [...mimarFlags].forEach((flag) => assert.match(flag, /^[a-z0-9][a-z0-9._-]{0,39}$/));
  assertUnique(data.regions, 'Bölge');
  assertUnique(data.islands, 'Ada');
  assertUnique(data.bridges, 'Ada köprüsü');
  assertUnique(data.regionBridges, 'Bölge köprüsü');
  assertUnique(phrases, 'Not cümlesi');
  const islandIds = new Set(data.islands.map(({ id }) => id));
  data.regions.forEach((region) => region.islands.forEach((islandId) => {
    assert.ok(islandIds.has(islandId), `${region.id} bilinmeyen ada içeriyor: ${islandId}`);
  }));
}

function assertUnique(items, label) {
  assert.equal(new Set(items.map(({ id }) => id)).size, items.length, `${label} ID’leri benzersiz olmalı`);
}

function formatList(values, spaces, perLine = 5) {
  const indent = ' '.repeat(spaces);
  const chunks = [];
  for (let index = 0; index < values.length; index += perLine) {
    chunks.push(`${indent}${values.slice(index, index + perLine).map(quote).join(', ')}`);
  }
  return chunks.join(',\n');
}

function inlineList(values) {
  return `[${values.map(quote).join(', ')}]`;
}

function exactPattern(values) {
  values.forEach((value) => assert.match(value, /^[A-Za-z0-9-]+$/));
  return `^(${values.join('|')})$`;
}

function quote(value) {
  assert.match(value, /^[A-Za-z0-9._-]+$/, `Rules için güvenli olmayan değer: ${value}`);
  return `'${value}'`;
}
