import assert from 'node:assert/strict';
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const projectRoot = fileURLToPath(new URL('..', import.meta.url));
const worldPath = new URL('../src/world.json', import.meta.url);
const rulesPath = new URL('../firestore.rules', import.meta.url);
const world = JSON.parse(await readFile(worldPath, 'utf8'));

validateWorldInputs(world);

const rules = generateRules(world);
const estimate = estimateWorstCaseExpressions(world);
reportEstimate(estimate);

if (process.argv.includes('--check')) {
  const committedRules = await readFile(rulesPath, 'utf8');
  assert.equal(
    committedRules,
    rules,
    'firestore.rules güncel değil; npm run gen:rules çalıştırın',
  );
  console.log('firestore.rules world.json ile birebir güncel');
} else {
  await writeFile(rulesPath, rules, 'utf8');
  console.log(`firestore.rules üretildi: ${fileURLToPath(rulesPath)}`);
}

function generateRules(data) {
  const regionIds = data.regions.map((region) => region.id);
  const islandIds = data.islands.map((island) => island.id);
  const bridgeIds = data.bridges.map((bridge) => bridge.id);
  const regionBridgeIds = data.regionBridges.map((bridge) => bridge.id);
  const playerFields = [
    'nickname', 'createdAt', 'lastSeenAt', 'activeRegionId', 'currentIslandId',
    'solved', 'openBridges', 'openRegionBridges', 'schemaVersion',
  ];
  const regionIslandChecks = data.regions
    .map((region, index) => {
      const prefix = index === 0 ? '        (' : '        || (';
      return `${prefix}data.activeRegionId == '${region.id}' && ${inlineList(region.islands)}.hasAny([data.currentIslandId]))`;
    })
    .join('\n');

  return `// Generated by scripts/gen-rules.mjs from src/world.json. Do not edit by hand.
rules_version = '2';

service cloud.firestore {
  match /databases/{database}/documents {
    function ownsPlayer(uid) {
      return request.auth != null && request.auth.uid == uid;
    }

    function validPlayerKeys(data) {
      return data.keys().hasAll([
${formatList(playerFields, 8)}
      ]) && data.keys().hasOnly([
${formatList(playerFields, 8)}
      ]);
    }

    function validNickname(nickname) {
      return nickname is string && nickname.size() >= 3 && nickname.size() <= 40;
    }

    function validRegionAndIsland(data) {
      return ${inlineList(regionIds)}.hasAny([data.activeRegionId])
        && (
${regionIslandChecks}
        );
    }

    function validSolvedRecord(record) {
      return record is map
        && record.keys().hasAll(['solvedAt', 'durationMs', 'attempts'])
        && record.keys().hasOnly(['solvedAt', 'durationMs', 'attempts'])
        && (record.solvedAt == null || record.solvedAt is timestamp)
        && record.durationMs is int
        && record.durationMs >= 0
        && record.attempts is int
        && record.attempts > 0;
    }

    function validSolvedShape(solved) {
      return solved is map
        && solved.size() <= ${islandIds.length}
        && solved.keys().hasOnly([
${formatList(islandIds, 8)}
        ]);
    }

    // Firestore Rules has a 1,000-expression runtime limit. Every changed
    // puzzle record is validated as it enters the document; unchanged records
    // were validated by their own earlier write.
    function validSolvedUpdate(after, before, currentIslandId) {
      let changedKeys = after.diff(before).affectedKeys();
      return changedKeys.size() == 0
        || after.size() == 0
        || (
          changedKeys.hasOnly([currentIslandId])
          && after.keys().hasAny([currentIslandId])
          && validSolvedRecord(after[currentIslandId])
        );
    }

    function validOpenBridges(openBridges) {
      return openBridges is list
        && openBridges.size() <= ${bridgeIds.length}
        && openBridges.size() == openBridges.toSet().size()
        && openBridges.hasOnly([
${formatList(bridgeIds, 8)}
        ]);
    }

    function validOpenRegionBridges(openRegionBridges) {
      return openRegionBridges is list
        && openRegionBridges.size() <= ${regionBridgeIds.length}
        && openRegionBridges.size() == openRegionBridges.toSet().size()
        && openRegionBridges.hasOnly([
${formatList(regionBridgeIds, 8)}
        ]);
    }

    function validPlayer(data) {
      return validPlayerKeys(data)
        && data.schemaVersion == 1
        && validNickname(data.nickname)
        && data.createdAt is timestamp
        && data.lastSeenAt is timestamp
        && validRegionAndIsland(data)
        && validSolvedShape(data.solved)
        && validOpenBridges(data.openBridges)
        && validOpenRegionBridges(data.openRegionBridges);
    }

    match /players/{uid} {
      allow read: if ownsPlayer(uid);
      allow create: if ownsPlayer(uid)
        && validPlayer(request.resource.data)
        && request.resource.data.solved.size() == 0
        && request.resource.data.createdAt == request.time
        && request.resource.data.lastSeenAt == request.time;
      allow update: if ownsPlayer(uid)
        && validPlayer(request.resource.data)
        && validSolvedUpdate(
          request.resource.data.solved,
          resource.data.solved,
          request.resource.data.currentIslandId
        )
        && request.resource.data.createdAt == resource.data.createdAt;
      allow delete: if false;
    }

    match /{document=**} {
      allow read, write: if false;
    }
  }
}
`;
}

function estimateWorstCaseExpressions(data) {
  // Conservative static approximation: fixed validation operators/function
  // calls plus every generated list literal. The emulator test remains the
  // authoritative guard for Firestore's runtime-dependent accounting.
  const fixedValidationCost = 220;
  const playerFieldLiterals = 9 * 2;
  const generatedIdLiterals = data.regions.length
    + data.regions.reduce((sum, region) => sum + region.islands.length, 0)
    + data.islands.length
    + data.bridges.length
    + data.regionBridges.length;
  return {
    estimated: fixedValidationCost + playerFieldLiterals + generatedIdLiterals,
    warningAt: 750,
    limit: 1000,
  };
}

function reportEstimate({ estimated, warningAt, limit }) {
  const percent = Math.round((estimated / limit) * 100);
  console.log(`Rules ifade tahmini: ${estimated}/${limit} (%${percent})`);
  if (estimated >= limit) {
    throw new Error(`Tahmini rules ifade maliyeti ${limit} sınırını aşıyor`);
  }
  if (estimated >= warningAt) {
    console.warn(`UYARI: Tahmini rules maliyeti ${warningAt} uyarı eşiğine ulaştı`);
  }
}

function validateWorldInputs(data) {
  for (const key of ['regions', 'islands', 'bridges', 'regionBridges']) {
    assert.ok(Array.isArray(data[key]), `world.json ${key} listesi içermeli`);
  }
  const islandIds = new Set(data.islands.map((island) => island.id));
  assert.equal(islandIds.size, data.islands.length, 'Ada ID’leri benzersiz olmalı');
  for (const region of data.regions) {
    assert.ok(region.islands.length > 0, `${region.id} en az bir ada içermeli`);
    region.islands.forEach((islandId) => {
      assert.ok(islandIds.has(islandId), `${region.id} bilinmeyen ada içeriyor: ${islandId}`);
      assert.equal(
        data.islands.find((island) => island.id === islandId)?.regionId,
        region.id,
        `${islandId} bölge listesiyle tutarsız`,
      );
    });
  }
  assertUniqueIds(data.regions, 'Bölge');
  assertUniqueIds(data.bridges, 'Ada köprüsü');
  assertUniqueIds(data.regionBridges, 'Bölge köprüsü');
}

function assertUniqueIds(items, label) {
  assert.equal(new Set(items.map((item) => item.id)).size, items.length, `${label} ID’leri benzersiz olmalı`);
}

function formatList(values, spaces, perLine = 5) {
  const indent = ' '.repeat(spaces);
  const chunks = [];
  for (let index = 0; index < values.length; index += perLine) {
    chunks.push(`${indent}${values.slice(index, index + perLine).map(quote).join(', ')}`);
  }
  return chunks.join(',\n');
}

function inlineList(values) {
  return `[${values.map(quote).join(', ')}]`;
}

function quote(value) {
  assert.match(value, /^[A-Za-z0-9-]+$/, `Rules için güvenli olmayan değer: ${value}`);
  return `'${value}'`;
}
