export const NOTE_PHRASES = Object.freeze([
  { id: 'surprising-rule', text: 'Bu adanın kuralı beni şaşırttı' },
  { id: 'second-try', text: 'İkinci denemede köprü açıldı' },
  { id: 'watch-the-bridge', text: 'Köprüye yaklaşınca çevrene bak' },
  { id: 'think-calmly', text: 'Sakin kalınca yol belirginleşiyor' },
  { id: 'study-shapes', text: 'Şekiller beklenmedik biçimde birleşiyor' },
  { id: 'looks-hard', text: 'İlk bakışta zor görünen bir ada' },
  { id: 'small-clue', text: 'Küçük ayrıntılar yolu gösteriyor' },
  { id: 'try-again', text: 'Başka bir deneme yeni bir yol açabilir' },
  { id: 'read-carefully', text: 'Adanın kenarlarında gizli bir iz var' },
  { id: 'fun-surprise', text: 'Sonunda güzel bir sürpriz var' },
  { id: 'take-your-time', text: 'Acele etmeden adayı keşfet' },
  { id: 'notice-pattern', text: 'Tekrar eden şekillere dikkat' },
  { id: 'different-angle', text: 'Başka bir açıdan bakınca değişiyor' },
  { id: 'count-twice', text: 'Parçaların sayısı yolu değiştiriyor' },
  { id: 'follow-order', text: 'Adımların sırası köprüyü etkiliyor' },
  { id: 'trust-first-clue', text: 'İlk gördüğün işareti unutma' },
  { id: 'clever-island', text: 'Bu adanın düzeni çok zekice' },
  { id: 'favorite-so-far', text: 'Şimdiye kadarki favori adam' },
  { id: 'almost-there', text: 'Bir deneme daha, köprü çok yakın' },
  { id: 'check-colors', text: 'Renkler arasında bir bağ var' },
  { id: 'simple-start', text: 'En küçük şekilden başlamak işe yarıyor' },
  { id: 'remember-path', text: 'Geldiğin yolu hatırlamak kolaylaştırıyor' },
  { id: 'good-luck', text: 'Sıradaki gezgine bol şans' },
  { id: 'worth-solving', text: 'Bu adayı çözmek çok keyifli' },
  { id: 'one-step-at-time', text: 'Her deneme yolu biraz daha açıyor' },
  { id: 'look-at-edges', text: 'Köprünün iki ucunu karşılaştır' },
  { id: 'nice-challenge', text: 'Bu adanın zorluğu tam kararında' },
  { id: 'keep-curious', text: 'Merak ettikçe yeni şekiller görünüyor' },
]);

export const NOTE_PHRASE_BY_ID = new Map(NOTE_PHRASES.map((phrase) => [phrase.id, phrase]));
